function Hd = Butt_bandpass_8(Fc1,Fc2,Fs)
%BUTT_BANDPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
% Generated on: 23-Jan-2019 16:40:18

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
% Fs = 30000;  % Sampling Frequency

N   = 8;     % Order
%Fc1 = 250;   % First Cutoff Frequency
%Fc2 = 3000;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
