function Hd = Butt_low_pass(Fpass,Fstop,Attenuationstop,Fs)
%BUTT_LOW-PASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 20-Mar-2018 14:30:54

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
%Fs = 30000;  % Sampling Frequency

%Fpass = 180;         % Passband Frequency
%Fstop = 200;         % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
%Astop = 12;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Attenuationstop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
